### ISSUE TITLE
Error when trying Char Sync in Warehouse

### ISSUE THREAD

**Issue by gOOvER** [Rythal/Carbonite#178]
1x Carbonite.Warehouse\NxWarehouse.lua:573: attempt to call method 'ImportCharacterData' (a nil value)
Carbonite.Warehouse\NxWarehouse.lua:573: in function `Func'
Carbonite\NxUI.lua:4758: in function <Carbonite\NxUI.lua:4728>

Locals:
self = <unnamed> {
 NxMenuItem = <table> {
 }
 0 = <userdata>
 texture = <unnamed> {
 }
}
button = "LeftButton"
this = <unnamed> {
 NxMenuItem = <table> {
 }
 0 = <userdata>
 texture = <unnamed> {
 }
}
item = <table> {
 AlphaTarget = 0.9
 User = <table> {
 }
 Id = 0
 Text = "Benutzerkontodatei syncronisieren"
 Func = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:572
 Menu = <table> {
 }
 Frm = <unnamed> {
 }
 TextFStr = <unnamed> {
 }
 Alpha = 0.80000004172325
 ShowState = 1
}

**Comment by atk** [comment]
Should be fixed with my latest commit. Can you please test it, too? Thanks.

**Comment by gOOvER** [comment]
I will test it tomorrow Morning :) ty for the fix :+1:

**Comment by atk** [comment]
Can we close that now?

**Comment by samyonair** [comment]
No it is not fixed no the failure only is  Carbonite.Warehouse\NxWarehouse.lua:578: attempt to call method 'ImportDo' (a nil value

**Comment by atk** [comment]
OK, should be fixed now.

**Comment by samyonair** [comment]
It seems to be fixed, in english but we have a problem in German client, cannot figure out why but Itemtypes seems to miss reagent in German files get errors if I Open Warehouse

3x Carbonite\NxUI.lua:3534: attempt to index field '?' (a nil value)
Carbonite\NxUI.lua:3534: in function `SetType'
Carbonite\NxUI.lua:5734: in function `Update'
Carbonite.Warehouse\NxWarehouse.lua:1045: in function `Update'
Carbonite.Warehouse\NxWarehouse.lua:469: in function `Create'
Carbonite.Warehouse\NxWarehouse.lua:618: in function `ToggleShow'
Carbonite.Warehouse\NxWarehouse.lua:2468: in function `func'
Carbonite\NxUI.lua:7110: in function `UserFunc'
Carbonite\NxUI.lua:3713: in function <Carbonite\NxUI.lua:3697>

Locals:
self = <table> {
 SelFrm = <unnamed> {
 }
 LineHPad = 4
 MinW = 2
 Vis = 33
 HdrH = 12
 Data = <table> {
 }
 BaseLineH = 16
 UserFunc = <function> defined @Carbonite.Warehouse\NxWarehouse.lua:646
 Selected = 0
 HdrFrm = <unnamed> {
 }
 ButData = <table> {
 }
 Num = 28
 Columns = <table> {
 }
 User = <table> {
 }
 SSW = 419.66668701172
 SSH = 550.00006103516
 Buts = <table> {
 }
 UsedFrms = <table> {
 }
 Top = 1
 Font = "Font.Medium"
 Sorted = false
 Frm = <unnamed> {
 }
 FontObj = NxFontM {
 }
 MinH = 1
 Strs = <table> {
 }
 Slider = <table> {
 }
}
showLast = nil
lineH = 16
hdrH = 12
last = 28
strNum = 67
cNum = 3
padW = 1
padH = 0
butNum = 1
f = <unnamed> {
 0 = <userdata>
 NxInst = <table> {
 }
 texture = <unnamed> {
 }
}
offX = 0
offY = 0
adjY = 20.5
(for index) = 1
(for limit) = 33
(for step) = 1
n = 1
line = 1
but = <table> {
 Frm = <unnamed> {
 }
 UserFunc = <function> defined @Carbonite\NxUI.lua:6447
 User = <table> {
 }
}
butType = "Lager"
L = <table> {
 Fireweed = "Feuerwurz"
 Dragonblight = "Drachenöde"
 Bloodwatcher Point, Badlands = "Blutwächterposten, Ödland"
 Westfall = "Westfall"
 Abyssal Depths = "Abyssische Tiefen"
 Stormshield = "Sturmschild"
 Options have been reset for the new version. = "Optionen wurden für die neue Version zurückgesetzt"
 Archaeology Blob Transparency = "Ausgrabungsort-Transparenz"
 Map Mouse Button Binds = "Karten-Mausverhalten"
 Shadowmoon Village, Shadowmoon Valley = "Schattenmond, Schattenmondtal"
 Opening = "Öffnen"
 Darnassus = "Darnassus"
 Menus = "Menüs"
 Gilneas = "Gilneas"
 Reset global options = "Globale  Einstellungen zurücksetzen"
 Left-Click to Toggle Map = "Linksklick, um die Karte ein-/auszublenden"
 Imported = "Importiert"
 Un'Goro Crater = "Krater von Un'Goro"
 Dustwind Dig, Badlands = "Staubwindausgrabung, Ödland"
 Stygian Bounty, Vashj'ir = "Höllenjuwel, Vashj'ir"
 Kirthaven, Twilight Highlands = "Kirthafen, Schattenhochland"
 Western Plaguelands = "Westliche Pestländer"
 The Jade Forest = "Der Jadewald"
 Middle-Click to Toggle Guide = "Mittel-Klick, um den Wegweiser ein-/auszublenden"
 Shrine of Seven Stars = "Schrein der Sieben Sterne"
 Max Vendors To Record = "Max. Länge Händlerverlauf"
 Crypt of Forgotten Kings = "Gruft der Vergessenen Könige"
 Left click toggle Map = "Linksklick blendet die Karte ein/aus"
 Flamestar Post, Burning Steppes = "Flammensternposten, Brennende Steppe"
 Sets the action performed when middle clicking holding CTRL = "Legt fest, welche Aktion ausgeführt wird, wenn ein Mittelklick bei gehaltener Strg-Taste erfolgt."
 Report Status = "Statusbericht"
 Winterspring = "Winterquell"
 Main Options = "Haupteinstellungen"
 Flying = "Fliegen"
 Com %d Bytes sec %d = "Com %d Bytes sek %d"
 Darkshore = "Dunkelküste"
 Dark Heart of Pandaria = "Das dunkle Herz Pandarias"
 Paladin Trainer = "Paladinlehrer"
 Small Font = "Kleine Schrift"
 Frostweed = "Frostwurz"
 Show Received Levelups = "Zeige empfangene Level-Steigerungen"
 Gold Vein = "Goldader"
 Onyxia's Lair = "Onyxias Hort"
 Apexis Excavation, Spires of Arak = "Apexisausgrabung, Spitzen von Arak"
 When enabled, the full size map will ignore all mouse clicks unless the ALT key is held down. = "Wenn aktiv, wird die Maus auf der Vollbild-Karte ignoriert, außer wenn die Alt-Taste gedrückt ist."
 Trainer = "Lehrer"
 Ethel Rethor, Desolace = "Ethel Rethor, Desolace"
 Sets the size of the player arrow on the map = "Legt die Größe des Spielerpfeils auf der Karte fest."
 Nijel's Point, Desolace = "Die Nijelspitze, Desolace"
 Show On All Continents = "Auf allen Kontinenten zeigen"
 Loading = "Laden"
 Hellscream's Fist, Kun-Lai Summit = "der Schlangenrücken, Kun-Lai Gipfel"
 Silverleaf = "Silberblatt"
 Docking Below Map Scale = "Unterhalb Kartenskalierung anhängen"
 Default Chat Channel = "Standard-Chat-Kanal"
 Gundrak, Zul'Drak = "Gundrak, Zul'Drak"
 When enabled, Shows your current movement speed in the titlebar. = "Wenn aktiv, wird die derzeitige Reisegeschwindigkeit in der Titelzeile der Karte angezeigt."
 Nagrand Arena = "Arena von Nagrand"
 Azsh

**Comment by atk** [comment]
I'll have a look at that later.

**Comment by samyonair** [comment]
OK we can close this Issue, other is Language Issue, don't make a new one we know now what to do
